language: node_js

node_js:
  - "stable"

env:
  - NODE_ENV=test

services:
  - postgresql

before_script:
  - psql -c 'create database test;' -U postgres

cache:
  directories:
    - "node_modules"

after_success:
  - npm run coverage